### ISSUE TITLE
Opening Submissions fails

### ISSUE THREAD

**Issue by jonas-w** [SimonHalvdansson/Harmonic-HN#55] opened 2023-08-12 22:24 UTC
When viewing a users submissions in the app you can't click on the submission directly. Opening the comments works and opening the submission from there works too.

But in the submission view it fails with the toast message "Couldn't open link to: https://[..]"

![Screenshot_20230813_002323_Harmonic.png](https://github.com/SimonHalvdansson/Harmonic-HN/assets/32615971/ef40090c-5ab5-44be-8d52-caa8ed36265c)

**Comment by SimonHalvdansson** [comment] 2023-08-12 22:28
I just tried this with the same user and was unable to reproduce the issue.

**Comment by SimonHalvdansson** [comment] 2023-08-13 11:32
This looks right, I'll take a look as soon as I get a chance but I have an idea what might be wrong. Thanks for the troubleshooting and reporting! 🙂

**Comment by SimonHalvdansson** [comment] 2023-08-14 17:52
Juding by the first line of the stack trace, I believe the error was that starting an intent from SubmissionsActivity used the application context instead of the activity context. This was just changed in a commit so I'll close the issue for now but please reopen it (or submit a new one if the issue persists after the next release). Thanks for the help!

**Closed by SimonHalvdansson** 2023-08-14 17:52 UTC
